version: "3.9"

services:
  app:
    image: __ACCOUNT_ID__.dkr.ecr.us-east-2.amazonaws.com/__ECR_REPOSITORY__:__HASH_TAG_BY_DEPLOY_ENV__
    container_name: ${CONTAINER_NAME:-fargate_service}
    ports:
      - "${PORT:-8123}:${CONTAINER_PORT:-8000}"
    restart: unless-stopped
