version: 0.0
files:
  - source: docker-compose.yml
    destination: __DEPLOY_PATH__/
  - source: .aws/cicd
    destination: __DEPLOY_PATH__/cicd/
hooks:
  ApplicationStart:
    - location: .aws/cicd/deploy.sh
      timeout: 300
      runas: ubuntu
